### ISSUE TITLE
[Feat] 대화 학습 화면 구현

### ISSUE THREAD

**Issue by JMM00** [CSID-DGU/2023-S-VSA-CoCo-1#1]
## TODO
- [x] 1,2,3단계 학습하기 화면 구현
- [x] text input 받기

---
- [x] 음성인식 화면 디자인 (피그마)
---
- [x] 음성인식 연결하기
- [x] tts 기능 연결

---
## ISSUE
- 안드로이드의 경우 라이브러리의 이슈로 인해 TextInput이 키보드 영역보다 아래에 있는 경우 바로 닫히는 문제 발생
    - 참고사이트: https://stackoverflow.com/questions/71227463/react-native-textinput-closes-automatically-when-opened-on-android
    - 위의 사이트에서 나오는 해결방법 통하지 않음
