### ISSUE TITLE
[Feat] 설정 화면 UI 및 기능 구현

### ISSUE THREAD

**Issue by JMM00** [CSID-DGU/2023-S-VSA-CoCo-1#6]
## TODO
- [x] 일주일 학습 목표 설정 UI
- [x] 최종 학습 완료 목표일 설정 UI
- [x] 회원 세부 정보 UI
