### ISSUE TITLE
[Feat] 한줄 학습 화면 구현

### ISSUE THREAD

**Issue by ParkHyeLim** [CSID-DGU/2023-S-VSA-CoCo-1#7]
## TODO
- [x] Library 화면 구현
- [x] 학습 화면 구현
- [x] DB 연동(Library 화면)
- [x] TTS 연결(학습 화면)
